<?php

/**
 * @file
 * Autogenerated class mapper
 *
 * All Eme code is released under the GNU General Public License.
 */
return [
    'E' => [
        'Eme\\Core\\' => 'C:/github/eme/eme/core',
        'Eme\\Core\\Autoload\\' => 'C:/github/eme/eme/core/Autoload',
        'Eme\\Core\\Autoload\\Exception\\' => 'C:/github/eme/eme/core/Autoload/Exception',
        'Eme\\Core\\Error\\' => 'C:/github/eme/eme/core/Error',
        'Eme\\Core\\FileSystem\\' => 'C:/github/eme/eme/core/FileSystem',
        'Eme\\Core\\FileSystem\\Exception\\' => 'C:/github/eme/eme/core/FileSystem/Exception',
        'Eme\\Core\\Finder\\' => 'C:/github/eme/eme/core/Finder',
        'Eme\\Core\\Util\\' => 'C:/github/eme/eme/core/Util',
    ],
];
