<?php

/**
 * Header comment
 * phpcs:disable
 */
if (!function_exists('eme_copyright')) {
    function eme_copyright()
    {
$comment = <<<HEAD
 * This file is part of Eme.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
HEAD;
        return $comment;
    }
}
/**
 * Autoloader header
 */
if (!function_exists('eme_autoloader_header')) {
    function eme_autoloader_header()
    {
        $eme_copyright = eme_copyright();
$comment = <<<HEAD
/**
 $eme_copyright
 * @file
 * Autogenerated class mapper
 *
 * IMPORTANT! Do not modify this file
 *
 */
HEAD;
    return $comment;
    }
}
// phpcs:enabled
